---
# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  docs-folder:  # id of input
    description: 'Folder to be used during make building'
    required: true
    default: 'docs'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docs-folder }}